version: '3.8'

services:
  tlytics:
    image: t0mk/tlytics:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    volumes:
      - ./data:/data
    environment:
      - TLYTICS_DB=/data/analytics.sqlite
    command: ["./tlytics", "--db", "/data/analytics.sqlite", "--port", "8081", "--flush", "5s"]
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:8081/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  data:
    driver: local
